Fix/various issues 221219
culturesofknowledge/site-edit-2 pull request #55
Opened 2022-12-19 19:04 UTC by J4bbi

- Creates a default sort property that can be set for each entity
- Fixes the empty check for columns
- Changes related objects for repositories to be a M2M field. If you think this will work fine @philipkcl  then I will proceed to do the same change for the other entities.

2022-12-20 10:08 UTC, philipkcl commented on institution/views.py
> +                                              'images__licence_details']})
as your mention, we can query m2m field by `Model.objects.filter(resources__resource_name='aaa')`


is it Django also support m2m field in F function `F('resources__resource_name')`?

2022-12-22 11:00 UTC, philipkcl requested changes

2022-12-22 12:41 UTC, J4bbi commented on core/management/commands/data_migration.py
> +    row['iperson_id'] = person_id
Resolved with https://github.com/culturesofknowledge/site-edit-2/pull/55/commits/454887b1f057388039a404db05c5cf42d075b972

2022-12-22 12:54 UTC, J4bbi commented on core/management/commands/data_migration.py
> +        row['union_iperson_id'] = union_person.pk
Resolved with https://github.com/culturesofknowledge/site-edit-2/pull/55/commits/3acb8189b54411c92bb642b2e702376273b8dbbe

2022-12-22 13:28 UTC, J4bbi commented on person/templates/person/search_table_layout.html
> +                {{ r.iperson_id }}</br>
Resolved https://github.com/culturesofknowledge/site-edit-2/pull/55/commits/d36e6778a7e06a8de3902791c90499cac927d884

2022-12-22 13:28 UTC, J4bbi commented on core/management/commands/data_migration.py
> +        row['repository_id'] = union_work.pk
Resolved https://github.com/culturesofknowledge/site-edit-2/pull/55/commits/d36e6778a7e06a8de3902791c90499cac927d884

2022-12-22 16:08 UTC, merged