Feature/17 UI for create users  3
culturesofknowledge/site-edit-2 pull request #6
Opened 2022-06-24 09:52 UTC by philipkcl

Fix admin page create user fail .

Related issues:
* https://github.com/culturesofknowledge/emlo-project/issues/20
* https://github.com/culturesofknowledge/emlo-project/issues/21
* https://github.com/culturesofknowledge/emlo-project/issues/17

2022-06-28 14:51 UTC, J4bbi requested changes
At this stage I don´t think we need a custom `UserManager`, since we are still using the same main user properties as the default user (email and passw).

However, the admin user change form don´t hash the password. @philipkcl , could you either follow the suggestions I posted as a comment [here](https://github.com/culturesofknowledge/site-edit-2/pull/2/files/a7275e840834d3de3a3012f49c6953b9ae0a1224#diff-f906c2dd0da247d64b767588df0542d6d86bbb11c1d30bfc19753123aa82cf1b), or perhaps use [AdminPasswordChangeForm](https://docs.djangoproject.com/en/4.0/topics/auth/default/#django.contrib.auth.forms.AdminPasswordChangeForm) ?

2022-06-28 14:51 UTC, J4bbi commented on login/forms.py
> +class CustomUserCreationForm(UserCreationForm):
`CofkUserCreationForm`

2022-07-01 10:09 UTC, philipkcl commented on login/admin.py
> +class CustomUserAdmin(UserAdmin):
but every class with prefix Cofk could be redundant, some time is also make confuse with models class, I would like to keep the `CustomUserAdmin`

2022-07-01 11:45 UTC, philipkcl commented
> At this stage I don´t think we need a custom `UserManager`, since we are still using the same main user properties as the default user (email and passw).
> 
> However, the admin user change form don´t hash the password. @philipkcl , could you either follow the suggestions I posted as a comment [here](https://github.com/culturesofknowledge/site-edit-2/pull/2/files/a7275e840834d3de3a3012f49c6953b9ae0a1224#diff-f906c2dd0da247d64b767588df0542d6d86bbb11c1d30bfc19753123aa82cf1b), or perhaps use [AdminPasswordChangeForm](https://docs.djangoproject.com/en/4.0/topics/auth/default/#django.contrib.auth.forms.AdminPasswordChangeForm) ?

tested `admin user change form` is hashed the password now. Could you show me the step that making non hashed password.

2022-07-06 22:38 UTC, merged