Features/230306 export data
culturesofknowledge/site-edit-2 pull request #75
Opened 2023-03-13 12:51 UTC by philipkcl

2023-03-13 16:33 UTC, J4bbi requested changes
There will be some html and/or stuff that needs parsing in some fields from `CofkUnionQueryableWork`, such as images and manifestations, but these are not massive issues and can be resolved going forward.

2023-03-13 16:33 UTC, J4bbi commented on person/views.py
> +            "Other details",
Other details is repeated 2x

2023-03-13 16:33 UTC, J4bbi commented on core/helper/view_utils.py
> +        self.to_user_messages = ['File will be send to your email later.']
"File will be send to your email later." => "The selected data is being processed and will be sent to your email soon."

2023-03-13 16:33 UTC, J4bbi commented on core/templates/core/basic_search_page.html
> +            }
'Are you sure export Excel?' => 'Are you sure you want to export the search results to Excel?'

'Are you sure export ' + num_records + ' records in Excel? '=> 'Are you sure you want to export {num_records} search results to Excel?'

2023-03-14 14:36 UTC, philipkcl commented on core/export_data/excel_header_values.py
> +            "Is Organization (Y=yes;black=no)",
header copy from old excel, should be correct

2023-03-14 14:45 UTC, merged