Fix/save last modified data
culturesofknowledge/site-edit-2 pull request #76
Opened 2023-03-14 12:19 UTC by J4bbi

2023-03-15 10:58 UTC, philipkcl commented on institution/views.py
> +    inst: CofkUnionInstitution | None = get_object_or_404(CofkUnionInstitution, pk=pk)
typing should be 
`inst: CofkUnionInstitution = get_object_or_404(CofkUnionInstitution, pk=pk)`
because `get_object_or_404` never return None

2023-03-15 10:58 UTC, philipkcl commented on person/views.py
> +        self.person: CofkUnionPerson | None = get_object_or_404(CofkUnionPerson, iperson_id=pk)
self.person is not nullable

2023-03-15 10:58 UTC, philipkcl commented on publication/views.py
> +    pub: CofkUnionPublication | None = get_object_or_404(CofkUnionPublication, pk=pk)
not nullable

2023-03-16 15:40 UTC, philipkcl requested changes

2023-03-16 16:55 UTC, J4bbi commented on audit/forms.py
>      table_name = CharSelectField(choices=table_name_choices, )
The search seems to work fine when I test.

Howeer, all audit timestamps are recent, done on data migration.

2023-03-16 17:25 UTC, philipkcl commented on audit/forms.py
>      table_name = CharSelectField(choices=table_name_choices, )
my fault

2023-03-16 17:26 UTC, merged